{% set version = "0.1.2" %}

package:
  name: doltcli
  version: {{ version }}

build:
  script:
    - PIP_NO_INDEX="False" $PYTHON -m pip install --no-deps doltcli=={{ version }}

requirements:
  build:
    - python {{ python }}
    - pip
  run:
    - python
    - dataclasses

about:
  home: https://github.com/dolthub/doltcli
