{% set name = "doltcli" %}
{% set version = "0.1.4" %}
{% set sha = "(stdin)= 510e83da39532814e2a53d4a1d1ba50c271b2bb785b5d282d9fbd29d9d3e54d2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
requirements:
  build:
    - python >=3.6
    - pip
    - poetry
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - dataclasses

about:
  home: https://github.com/dolthub/doltcli
