{% set version = "0.1.4" %}

package:
  name: doltcli
  version: {{ version }}

buiLd:
  script:
    - PIP_NO_INDEX="False" $PYTHON -m pip install doltcli=={{ version }}

requirements:
  build:
    - python
  run:
    - python
    - dataclasses

about:
  home: https://github.com/dolthub/doltcli
