name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.23.4'
        required: true

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Update Doltcli version
        run: sed -i 's/version =.*/version = "'"$VERSION"'"/' "$FILE"
        env:
          FILE: setup.py
          VERSION: ${{ github.event.inputs.version }}
      - uses: EndBug/add-and-commit@v7
        with:
          message: ${{ format('[ga-bump-release] update Doltcli version to {0}', github.event.inputs.version) }}
          add: ${{ format('{0}/setup.py', github.workspace) }}
          cwd: "."
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
      - name: Checkout release
        run: |
          git fetch --tags --all
          git checkout tags/v${{ github.event.inputs.version }} -b v${{ github.event.inputs.version }}
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Publish
        run: ./scripts/release.sh
        env:
          PASSWORD: ${{ secrets.pypi_password }}
